name: ci

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  merge_group: {}

jobs:
  code-style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Add prettier dependencies
        run: pnpm add -g @trivago/prettier-plugin-sort-imports prettier eslint

      - name: Prettify code
        run: pnpm prettier --write src

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply prettier code styling
